create table "public"."user_info" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null
);


alter table "public"."user_info" enable row level security;

CREATE UNIQUE INDEX user_info_id_key ON public.user_info USING btree (id);

CREATE UNIQUE INDEX user_info_pkey ON public.user_info USING btree (id, created_at, username);

alter table "public"."user_info" add constraint "user_info_pkey" PRIMARY KEY using index "user_info_pkey";

alter table "public"."user_info" add constraint "user_info_id_key" UNIQUE using index "user_info_id_key";

grant delete on table "public"."user_info" to "anon";

grant insert on table "public"."user_info" to "anon";

grant references on table "public"."user_info" to "anon";

grant select on table "public"."user_info" to "anon";

grant trigger on table "public"."user_info" to "anon";

grant truncate on table "public"."user_info" to "anon";

grant update on table "public"."user_info" to "anon";

grant delete on table "public"."user_info" to "authenticated";

grant insert on table "public"."user_info" to "authenticated";

grant references on table "public"."user_info" to "authenticated";

grant select on table "public"."user_info" to "authenticated";

grant trigger on table "public"."user_info" to "authenticated";

grant truncate on table "public"."user_info" to "authenticated";

grant update on table "public"."user_info" to "authenticated";

grant delete on table "public"."user_info" to "service_role";

grant insert on table "public"."user_info" to "service_role";

grant references on table "public"."user_info" to "service_role";

grant select on table "public"."user_info" to "service_role";

grant trigger on table "public"."user_info" to "service_role";

grant truncate on table "public"."user_info" to "service_role";

grant update on table "public"."user_info" to "service_role";


